# Generated by Django 3.1.2 on 2021-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='desciption',
            new_name='desc',
        ),
    ]
